use_frameworks!

platform :ios, '9.0'

target 'RxSocket.io_Example' do
  pod 'RxSocket.io', :path => '../'

  target 'RxSocket.io_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.2.0'
    pod 'Nimble', '~> 8.0.7'
  end
end
